### ISSUE TITLE
Having trouble starting mod-app

### ISSUE THREAD

**Issue by randomas** [portalmod/mod-app#11]
I think I configured it right and jack is up. 

I'm getting this error (ubuntu 14.04 with kxstudio repo):
NOTE: Using custom mod-ui module
Using HMI => False
slot_backendStart in progress...
BACKEND: Cannot lock down 82274202 byte memory area (Cannot allocate memory)
BACKEND: mod-host ready!
Traceback (most recent call last):
  File "/home/matteo/src/mod-app-master/source/mod_host.py", line 77, in run
    webserver.prepare(True)
TypeError: prepare() takes 0 positional arguments but 1 was given
webserver finished

Is it just a case of not enough memory on the machine (old netbook) or is there something else?

**Comment by falkTX** [comment]
did you update mod-ui?

mod-app and mod-ui must be in sync to work. if you update one you need to update the other.

**Comment by randomas** [comment]
Oh ok, I just installed it from the kxstudio repos, so I'm using whatever is up on there. Do I have to get a fresh copy off git? 
Also the memory lock issue is to do with jack, but it seems to proceed quite happily in spite of it, happens on newer notebook with 4gb ram as well. 

Thanks!

**Comment by falkTX** [comment]
oh, you should have mentioned that first.
sometimes I forget to update the kxstudio stuff. will do that soon.

**Comment by randomas** [comment]
Oh ok, great!

Good to know I'm not the only one having trouble keeping up with everything. ;-)

Thanks!

**Comment by randomas** [comment]
Ok I tried doing a build with git mod-ui. I gave for garnted that make in root of mod-app will build all modules (is this true?)

After rebuilding I get this error:

OTE: Using custom mod-ui module
Traceback (most recent call last):
  File "./mod-app", line 22, in <module>
    from mod_host import *
  File "/home/matteo/src/mod-app-master/source/mod_host.py", line 55, in <module>
    from mod import webserver
  File "/home/matteo/src/mod-app-master/source/modules/mod-ui/mod/webserver.py", line 44, in <module>
    from mod.session import SESSION
  File "/home/matteo/src/mod-app-master/source/modules/mod-ui/mod/session.py", line 31, in <module>
    from mod.development import FakeHost, FakeHMI
  File "/home/matteo/src/mod-app-master/source/modules/mod-ui/mod/development.py", line 21, in <module>
    from mod.host import Host
  File "/home/matteo/src/mod-app-master/source/modules/mod-ui/mod/host.py", line 40, in <module>
    from mod.utils import (charPtrToString,
  File "/home/matteo/src/mod-app-master/source/modules/mod-ui/mod/utils.py", line 134, in <module>
    utils = cdll.LoadLibrary(tryPath2)
  File "/usr/lib/python3.4/ctypes/**init**.py", line 429, in LoadLibrary
    return self._dlltype(name)
  File "/usr/lib/python3.4/ctypes/__init__.py", line 351, in **init**
    self._handle = _dlopen(self._name, mode)
OSError: /home/matteo/src/mod-app-master/source/modules/mod-ui/mod/../utils/libmod_utils.so: cannot open shared object file: No such file or directory

Thanks.

**Comment by randomas** [comment]
hmm tried to make libmod_utils but it gives me lilv errors ... seems to not agree with kx studio lilv dev libraries ... 

I think it may be best if I wait for you to update kxstudio modui ...

**Comment by falkTX** [comment]
I'll update the kxstudio stuff sometime this week.

**Comment by randomas** [comment]
No worries, I was just hoping to be able to build it myself, but is seems to be a wee bit too much for me.

Thanks again.
