### ISSUE TITLE
mod-app on Arch Linux

### ISSUE THREAD

**Issue by jujudusud** [portalmod/mod-app#18]
I am actually trying to package mod-app for Arch Linux.
mod-host-git is ok.
mod-app and mod-ui are ok too.
when trying to launch the application:
```
$ mod-app
Using FakeHMI => <mod.development.FakeHMI object at 0x7f9178ee5e80>
cc start socket missing
ERROR: failed to open /home/julien/.local/share/mod-data/profile5.json
Traceback (most recent call last):
  File "/usr/share/mod-app/mod-app", line 22, in <module>
    from mod_host import *
  File "/usr/share/mod-app/mod_host.py", line 57, in <module>
    from mod import webserver
  File "/usr/lib/python3.9/site-packages/mod/webserver.py", line 278, in <module>
    class SimpleFileReceiver(JsonRequestHandler):
  File "/usr/lib/python3.9/site-packages/mod/webserver.py", line 289, in SimpleFileReceiver
    @web.asynchronous
AttributeError: module 'tornado.web' has no attribute 'asynchronous'
```

**Comment by falkTX** [comment]
use the submodules if you want this to work.
Also, the tool is not in the best shape at the moment, contributions welcome.

**Comment by jujudusud** [comment]
Ok thanks a lot for that.
Now I use submodules for mod-host and mod-ui.
There is another error that I don't know how to debug.
`$ mod-app
Traceback (most recent call last):
  File "/usr/share/mod-app/mod-app", line 22, in <module>
    from mod_host import *
  File "/usr/share/mod-app/mod_host.py", line 55, in <module>
    setInitialSettings()
  File "/usr/share/mod-app/mod_common.py", line 180, in setInitialSettings
    from mod import settings
ModuleNotFoundError: No module named 'mod'`

The Package is here: [https://aur.archlinux.org/packages/mod-app-git/](url)

**Comment by falkTX** [comment]
Don't install it, run it locally for now.
